name: build and run
on: [push]
jobs:
  build and run:
    runs-on: ubuntu-latest # change version
    steps:
      - uses: actions/checkout@4
      - run: g++ main.cpp my_add.cpp -o main 
      - run: ./main 50 40