name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest # change version
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      # - run: g++ main.cpp my_add.cpp -o main 
      - run: ./build/main 50 40